const blackSmallCircleImage = "assets/pics/black small circle.png";
const circlePartBottomCenterImage = "assets/pics/circle part bottom center.png";
const circlePartBottomLeftImage = "assets/pics/circle part bottom left.png";
const circleImage = "assets/pics/circle.png";
const quarterCircleTopRightImage = "assets/pics/quarter circle top right.png";
const redLineImage = "assets/pics/red line.png";
const searchIconImage = "assets/pics/search icon.png";
const smallerCircleImage = "assets/pics/smaller circle.png";
const backIconImage = "assets/pics/back_icon.png";